server:
  port: ${SERVER_PORT:8080}
management:
  endpoint:
    health:
      show-details: always
jag:
  efiling:
    diligen:
      health:
        enabled: ${DILIGEN_HEALTH_ENABLED:true}
      basePath: ${DILIGEN_BASE_PATH}
      username: ${DILIGEN_USERNAME}
      password: ${DILIGEN_PASSWORD}
