server:
  port: ${SERVER_PORT:8080}
management:
  endpoint:
    health:
      show-details: always
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin}
jag:
  efiling:
    diligen:
      health:
        enabled: ${DILIGEN_HEALTH_ENABLED:true}
      basePath: ${DILIGEN_BASE_PATH}
      username: ${DILIGEN_USERNAME}
      password: ${DILIGEN_PASSWORD}
      projectIdentifier: ${DILIGEN_PROJECT_IDENTIFIER}

bcgov:
  clamav:
    host: ${CLAMAV_HOST:localhost}
    port: ${CLAMAV_PORT:3310}
    timeout: ${CLAMAV_TIMEOUT:50000}
